### ISSUE TITLE
Broken link of PubSub documentation

### ISSUE THREAD

**Issue by EmrysMyrddin** [AlexMog/FFS-PubSub#1]
The documentation link for the PubSub documentation in the README is broken (Error 404).

The link to the Issues page is also broken since it redirect to the previous private GitLab

**Comment by AlexMog** [comment]
Thanks for the report, it's fixed :)

**Comment by EmrysMyrddin** [comment]
Issues page link is still wrong :-)

**Comment by AlexMog** [comment]
Are you sure? It seems to work on my side: https://github.com/AlexMog/FFS-PubSub/blob/master/README.md

**Comment by EmrysMyrddin** [comment]
Hummm strange, probably the cache ...
